version: "3.3"

services: 
    webserver: 
        build: '.docker/webserver/'
        ports: 
           - 80:80
        volumes: 
            - ./webroot:/var/www/html
            
    database:
        image: mysql:latest
        restart: always
        volumes: 
            - data:/var/lib/mysql
        environment:
                MYSQL_ROOT_PASSWORD: root

    adminer: 
        image: adminer:latest
        ports:
            - 8080:8080
volumes: 
    data: